version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    environment:
      - MONGODB_DATABASE=sdt
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
  minio:
    image: 'docker.io/minio/minio'
    environment:
      - MINIO_ACCESS_KEY=CHANGE_ME
      - MINIO_SECRET_KEY=CHANGE_ME
    ports:
      - '9000:9000'
    volumes:
      - 'minio_data:/data'
  sdf_server:
    image: 'docker.io/groens/sdf-server'
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=sdf
      - MONGODB_PASSWORD=sdfpw
      - MONGODB_DATABASE=sdf
      - EXPRESS_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6397
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=redispw
      - SECURITY_SECRET=MY_SECURITY_SECRET
      - SECURITY_EXPIRES_IN=30d
      - S3_END_POINT=http://192.168.17.33:9000
      - S3_ACCESS_KEY=MY_ACCESS_KEY
      - S3_SECRET_KEY=MY_SECRET_KEY
      - S3_FORCE_PATH_STYLE=true
      - S3_SIGNATURE_VERSION=v4
      - S3_DEFAULT_BUCKET=sdf-dev
      - LOCAL_DIR=public/upload/sdf-dev
      - LOCAL_END_POINT_URL=download
      - LOCAL_DOMAIN=http://localhost:8080
    ports:
      - '3000:8080'      
     
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
