version: '2'
services:
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    environment:
      - MONGODB_DATABASE=sdt
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  minio:
    image: 'minio/minio'
    environment:
      - MINIO_ACCESS_KEY=MY_ACCESS_KEY
      - MINIO_SECRET_KEY=MY_SECRET_KEY
    command: 'server /data'
    ports:
      - '9000:9000'
    volumes:
      - 'minio_data:/data'
  sdf_server:
    image: 'docker.io/groens/sdf-server'
    depends_on:
      - "redis"
      - "mongodb"
      - "minio"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
#      - MONGODB_USERNAME=sdf
#      - MONGODB_PASSWORD=sdfpw
      - MONGODB_DATABASE=sdf
      - EXPRESS_PORT=3000
      - REDIS_HOST=redis
#      - REDIS_PORT=6397
#      - REDIS_USERNAME=redis
#      - REDIS_PASSWORD=redispw
      - SECURITY_SECRET=MY_SECURITY_SECRET
      - SECURITY_EXPIRES_IN=30d
      - S3_END_POINT=http://192.168.17.33:9000
      - S3_ACCESS_KEY=MY_ACCESS_KEY
      - S3_SECRET_KEY=MY_SECRET_KEY
      - S3_FORCE_PATH_STYLE=true
      - S3_SIGNATURE_VERSION=v4
      - S3_DEFAULT_BUCKET=sdf-dev
      - LOCAL_DIR=public/upload/sdf-dev
      - LOCAL_END_POINT_URL=download
      - LOCAL_DOMAIN=http://localhost:8080
    ports:
      - '8080:3000'
  sdf_frontend:
    image: 'groens/sdt-frontend'
    environment:
      - SOCKETIO_ENDPOINT=http://localhost:8080
      - API_ENDPOINT=http://localhost:8080/api
      - DEMO=true
      - APP_NAME=SimpleDataTransfer
      - COPYRIGHT_STRING=&copy; 2020%year% <a href='https://github.mycoding.systems' class='link-color project-developer' target='_blank'> NGroens</a> - Dev-Build
      - SHOW_POWERED_BY=true
      - SHOW_VERSION=true
    ports:
      - '80:80'
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
